# Generated by Django 4.2 on 2023-05-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThreadId', models.CharField(max_length=100)),
                ('ExpiryTime', models.DateTimeField()),
            ],
        ),
    ]
