# Generated by Django 4.2 on 2023-05-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='id',
        ),
        migrations.AlterField(
            model_name='mail',
            name='ThreadId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
